### ISSUE TITLE
NW.js

### ISSUE THREAD

**Issue by TheJaredWilcurt** [EnderCommunity/EnderFramework#222]
Just throwing it out there that if you're building an abstraction layer, NW.js is a better choice than Electron. It has more powerful features, and specifically for what you're doing it would be extremely easy to create this project using it.

NW.exe can run by passing in a path to a project in a command: `C:\path\to\nw.exe "C:\path\to\project"` which can be created as desktop shortcuts. Or you can package a project in a zip and open it that way. or even rename the zip to any other extension and then associate that to the NW.js executable. So anytime someone downloads an `My-Cool-App.ender` and double-clicks it, it just launches with your `nw.exe`.

Just throwing it out there. NW is commonly used for stuff like this. Construct 2 is responsible for hundreds of thousands of games and it uses NW.js for packaging. Same thing for WeChat (chinese app store).

If you're not familiar with it, this site has a quick run down:

* https://xpda.net

The only real benefit Electron offers over it is ecosystem, which your users likely won't be taking advantage of.

**Comment by adel-sbeh** [comment]
I've looked into this, and it seems that NW.js would be a useful replacement.

**Comment by adel-sbeh** [comment]
@TheJaredWilcurt, is there a Discord server, or something else like this, for this project?

**Comment by TheJaredWilcurt** [comment]
* **Official chat:** https://gitter.im/nwjs/nw.js
* **Bug Tracker:** https://github.com/nwjs/nw.js/issues
* **Official Twitter:** https://twitter.com/nw_js
* **Common utility libraries/boilerplates:** https://NWUtils.io
* **Tutorials:** https://xpda.net/#NW.js
* **Official Google Group:** https://groups.google.com/forum/#!forum/nwjs-general (Though this might move to GH Discussions?)
* **Rarely used Subreddit:** https://old.reddit.com/nwjs

**Comment by TheJaredWilcurt** [comment]
@adel-sbeh There is also a Discord: https://discord.gg/tyx267vKRH
